<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <PackageProjectUrl>https://github.com/miserix13/WebNet.YarpDestinationDiscovery</PackageProjectUrl>
    <Authors>makutamiserix;miserix13</Authors>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.1.13" />
    <PackageReference Include="Take.Elephant.Redis" Version="0.10.210" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebNet.YarpDestinationDiscovery\WebNet.YarpDestinationDiscovery.csproj" />
  </ItemGroup>

</Project>
